In [48]:
import numpy as np
from scipy import sparse

# COO
# dense3 = np.array([[0,0,1,0,0,5,0,0,3,0],
#                   [1,4,0,3,2,5,0,0,0,0],
#                   [0,6,0,3,0,0,0,0,0,0],
#                    [2,0,0,0,0,0,1,0,0,0],
#                   [0,0,0,7,0,8,0,0,0,0],
#                   [1,0,0,0,0,0,0,0,0,0],
#                   [1,2,0,0,0,0,0,0,0,4],
#                   [0,0,0,5,6,7,0,0,0,0],
#                   [1,0,0,0,0,0,0,0,4,2],
#                   [4,0,0,3,0,0,0,0,2,0]])

# data3 = np.array([1,5,3,1,4,3,2,5,6,3,2,1,7,8,1,1,2,4,5,6,7,1,4,2,4,3,2])

# row_pos = np.array([0,0,0,1,1,1,1,1,2,2,3,3,4,4,5,6,6,6,7,7,7,8,8,8,9,9,9])
# col_pos = np.array([2,5,8,0,1,3,4,5,1,3,0,6,3,5,0,0,1,9,3,4,5,0,8,9,0,3,8])

# sparse_coo = sparse.coo_matrix((data3, (row_pos, col_pos)))
# sparse_coo.toarray()

In [51]:
# 0의 비율이 70% 이상인 희소행렬 만들기
dense3=np.zeros([10,10])
np.random.seed(0)
# np.random.choice(range(1,10),10)

for i in dense3:
    for num,j in enumerate(i):
        if num == np.random.randint(0,9):
            i[num] = np.random.randint(1,9)
dense3      

array([[0., 0., 0., 8., 0., 3., 0., 7., 1., 0.],
       [0., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 8., 0., 0., 5., 0., 0.],
       [5., 0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.]])

In [52]:
# 희소행렬 내에 data 뽑기
data3 = []
for i in dense:
    for j in i:
        if j != 0:
            data3.append(int(j))
data3=np.array(data3)
data3

array([8, 3, 7, 1, 2, 8, 5, 5, 2, 5, 5, 3, 3])

In [53]:
li = []
li2 = []
for num,i in enumerate(dense3):
    for num2,j in enumerate(i):
        if j != 0:
            li.append(num)
            li2.append(num2)
        
            
row_pos = np.array(li)       
col_pos = np.array(li2)

print(row_pos)
print(col_pos)
sparse_coo = sparse.coo_matrix((data3, (row_pos, col_pos)))
sparse_coo.toarray()

[0 0 0 0 1 3 3 4 4 6 6 8 9]
[3 5 7 8 5 4 7 0 8 3 4 3 3]


array([[0, 0, 0, 8, 0, 3, 0, 7, 1],
       [0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 8, 0, 0, 5, 0],
       [5, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0]])

In [54]:
csr = [0, len(li)]
# csr = []
for num,i in enumerate(range(len(li)-1)):
    if li[num] != li[num+1]:
        csr.append(num+1)

     
csr = sorted(csr)

print(csr)
row_pos_ind = np.array(csr)

sparse_csr = sparse.csr_matrix((data3, col_pos, row_pos_ind))

sparse_csr.toarray()

[0, 4, 5, 7, 9, 11, 12, 13]


array([[0, 0, 0, 8, 0, 3, 0, 7, 1],
       [0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 8, 0, 0, 5, 0],
       [5, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 5, 5, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0]])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# # TF-IDF 벡터화를 적용해 학습 데이터 세트와 테스트 데이터 세트 반환
tfidf_vect = TfidfVectorizer(stop_words = 'english', ngram_range=(1,2), max_df=300)
tfidf_vect.fit(X_train)
X_train_tfidf_vect = tfidf_vect.transform(X_train)
X_test_tfidf_vect = tfidf_vect.transform(X_test)

lr_clf = LogisticRegression(solver='liblinear')
lr_clf.fit(X_train_tfidf_vect, y_train)
pred = lr_clf.predict(X_test_tfidf_vect)
print(f'TF-IDF 벡터라이징 로지스틱 회귀 예측 정확도 : {round(accuracy_score(y_test,pred),3)}')